[project]
name = "decision-tree-breast-cancer-prediction-using-sugeno-algorithm-web-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
